### ISSUE TITLE
Please document this! 

### ISSUE THREAD

**Issue by sthulb** [iann0036/aws-account-controller#1]
I really want to use this.

**Comment by iann0036** [comment]
Still a work in progress to get everything set up. Currently stuck on index.js:672 (file upload) with the following error:

```
ERROR	Invoke Error 	
{
    "errorType": "Error",
    "errorMessage": "Evaluation failed: TypeError: Failed to fetch\n    at __puppeteer_evaluation_script__:4:32",
    "stack": [
        "Error: Evaluation failed: TypeError: Failed to fetch",
        "    at __puppeteer_evaluation_script__:4:32",
        "    at ExecutionContext._evaluateInternal (/var/task/node_modules/puppeteer-core/lib/ExecutionContext.js:122:13)",
        "    at runMicrotasks (<anonymous>)",
        "    at processTicksAndRejections (internal/process/task_queues.js:94:5)",
        "    at async ElementHandle.evaluateHandle (/var/task/node_modules/puppeteer-core/lib/JSHandle.js:63:12)",
        "    at async ElementHandle.uploadFile (/var/task/node_modules/puppeteer-core/lib/JSHandle.js:335:5)",
        "    at async createflow (/var/task/index.js:672:5)",
        "    at async Runtime.exports.handler (/var/task/index.js:983:9)",
        "  -- ASYNC --",
        "    at ExecutionContext.<anonymous> (/var/task/node_modules/puppeteer-core/lib/helper.js:111:15)",
        "    at ElementHandle.evaluateHandle (/var/task/node_modules/puppeteer-core/lib/JSHandle.js:63:42)",
        "    at ElementHandle.<anonymous> (/var/task/node_modules/puppeteer-core/lib/helper.js:112:23)",
        "    at ElementHandle.uploadFile (/var/task/node_modules/puppeteer-core/lib/JSHandle.js:335:16)",
        "    at async createflow (/var/task/index.js:672:5)",
        "    at async Runtime.exports.handler (/var/task/index.js:983:9)",
        "  -- ASYNC --",
        "    at ElementHandle.<anonymous> (/var/task/node_modules/puppeteer-core/lib/helper.js:111:15)",
        "    at createflow (/var/task/index.js:672:21)",
        "    at runMicrotasks (<anonymous>)",
        "    at processTicksAndRejections (internal/process/task_queues.js:94:5)",
        "    at async Runtime.exports.handler (/var/task/index.js:983:9)"
    ]
}
```

Creating the stack and executing the Lambda directly with:

```
{
  "properties": {
    "Domain": "somethinguniquehere"
  }
}
```

will replicate.

**Comment by iann0036** [comment]
Hey @sthulb,

FYI, I've composed the README now. The project is in a state where it works, but is not at all resilient to failure or unusual conditions. I'll be working on that shortly.

**Comment by sthulb** [comment]
Thanks Ian!
